import {
    attribute,
    autoGeneratedHashKey,
    table,
} from '@aws/dynamodb-data-mapper-annotations';

import { Models } from 'utilities-techsweave';

/*
 * This class rappresent a cart item in carts table
 */
@table(process.env.CATEGORIES_TABLE)
class Category implements Models.Tables.ICategory {
    @autoGeneratedHashKey()
    id: string;

    @attribute()
    name: string;

    @attribute()
    customSpecTemplates?: Models.Tables.ISpecTemplate[];

    @attribute()
    description?: string;

    @attribute()
    macroCategorieId?: string

    @attribute()
    taxes?: number
}

export default Category;